# Generated by Django 5.0.4 on 2024-06-06 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=70)),
                ('topic_title', models.CharField(max_length=80)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='image/', validators=[django.core.validators.validate_image_file_extension])),
                ('author', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
    ]
